[build]
publish = "public"
command = "hugo -c exampleSite --themesDir / --config exampleSite/config.toml --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.76.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo -c exampleSite --themesDir / --config exampleSite/config.toml --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.76.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -c exampleSite --themesDir / --config exampleSite/config.toml --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76.5"

[context.branch-deploy]
command = "hugo -c exampleSite --themesDir / --config exampleSite/config.toml --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
